### ISSUE TITLE
动态切换主题色

### ISSUE THREAD

**Issue by Liang-Feifei** [hzsrc/vue-element-ui-scaffold-webpack4#10]
您好，请问我使用vue-cli3搭建的项目使用您的webpack-theme-color-replacer插件动态切换主题色，为什么elementUI自己的组件可以切换成功，但是在scss里面使用$--color-primary变量却不会动态改变呢？

**Comment by hzsrc** [comment]
不清楚你的代码。参考vue-element-ui-scaffold-webpack4这个项目的做法。
