### ISSUE TITLE
webpack-theme-color-replacer@1.3.19存在报错问题

### ISSUE THREAD

**Issue by my3188** [hzsrc/vue-element-ui-scaffold-webpack4#15]
node_modules\webpack-theme-color-replacer\src\Handler.js   70行
![Snipaste_2021-04-17_17-03-12](https://user-images.githubusercontent.com/5450674/115107638-d741e080-9f9e-11eb-8e55-42af5c5667ce.png)
修改完之后的样子
这块应该是双引号

**Comment by staoran** [comment]
是的，实属不应该啊，写法应该向上两行那样，
configJs = configJs + `\n(typeof window=='undefined'?global:window).__theme_COLOR_css=' + JSON.stringify(cssCode.replace(LineReg, '')) + ';\n`

**Comment by hzsrc** [comment]
抱歉！改得急大意了。已修复了，感谢指正！
