### ISSUE TITLE
help! 关于分离element-ui的字体文件路径报错

### ISSUE THREAD

**Issue by Sliect** [hzsrc/vue-element-ui-scaffold-webpack4#2]
// 真实的输出路径 dist/pages/fonts
// 去寻找的输出路径 dist/pages/css/fonts
// 相当于相对于输出路径 (output.path)dist/pages/ + (MiniCssExtractPlugin)css/ + (file-loader.outputPath)fonst/
附上仓库地址 https://github.com/Sliect/webpack-path

**Comment by hzsrc** [comment]
参考下这个项目的源码试试。

**Comment by hzsrc** [comment]
今天碰到类似的问题解决了，试下这个

ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader',
        **publicPath: '../../'**
      })

**Comment by Sliect** [comment]
webpack4貌似不推荐用这个分离插件

**Comment by Sliect** [comment]
还有一种把文件移动到另一个文件的插件，也能解决问题，但是感觉没到问题的点子上

**Comment by Sliect** [comment]
现在用的是vue-cli3.0，就没这个问题,，我个人感觉是我的用法可能有问题，之前看的一个人的源码，我安装了element, 就没这个问题

**Comment by hzsrc** [comment]
MiniCssExtractPlugin应该有类似属性，可以去查下文档看

**Comment by Sliect** [comment]
当初查了2天没解决，放弃了

**Comment by Sliect** [comment]
就差去读webpack源码了

**Comment by hzsrc** [comment]
查了文档，确实有这个属性，你试下看：
https://www.npmjs.com/package/mini-css-extract-plugin

**Comment by Sliect** [comment]
bingo! 这次OK了，感谢大佬
