### ISSUE TITLE
前端学员一枚，求助，求解答一下

### ISSUE THREAD

**Issue by MrChenGG** [hzsrc/vue-element-ui-scaffold-webpack4#3]
这个切换主题我非常喜欢，但是我实现不来，下载了您的项目run了也没能切换成功，不知道是不是还需要其他服务的支持还是说我这边的操作有误，求助求助，如果可以的话可以微信加我（微信号：vin51921）预先感谢!!!

**Comment by hzsrc** [comment]
npm run dev就是如下的效果了：
http://test.hz300.com/webpack4/themeColor.html
代码都有，研究一下吧
