### ISSUE TITLE
请问一下VueLoader相关问题

### ISSUE THREAD

**Issue by shoyuf** [hzsrc/vue-element-ui-scaffold-webpack4#4]
vue-loader v15 [废弃](https://vue-loader.vuejs.org/zh/migrating.html#%E5%BA%9F%E5%BC%83%E7%9A%84%E9%80%89%E9%A1%B9) 了很多 options。为什么在 webpack.base.conf.js 中还使用 loaders 那些配置？

**Comment by hzsrc** [comment]
已修改。
