### ISSUE TITLE
关于 nuxt 生成css 文件为空文件

### ISSUE THREAD

**Issue by YikuanLu** [hzsrc/vue-element-ui-scaffold-webpack4#5]
nuxt 下配置完文件可以生成，但是生成的 css 文件为空

**Comment by hzsrc** [comment]
还请提供下重现步骤，或项目github地址

**Comment by hzsrc** [comment]
看下加上--theme_debug输出的临时文件内容是什么？
* https://github.com/hzsrc/webpack-theme-color-replacer：
`If you have issues with this plugin, please run your command with --theme_debug option, such as npm run dev --theme_debug, then upload the outputed _tmp_xxx files while reporting issues. Thanks!`
