### ISSUE TITLE
css/theme-colors-*.css file is empty

### ISSUE THREAD

**Issue by junhuafly** [hzsrc/vue-element-ui-scaffold-webpack4#6]
new ThemeColorReplacer({
        fileName: 'css/theme-colors-[contenthash:8].css', // output css file name, suport [contenthash] and [hash].
        matchColors: ['#ed4040', '#4b0'], // colors array for extracting css file
        resolveCss(resultCss) { // optional. Resolve result css code as you wish.
          return resultCss.replace(/#4b0/g, '#ed4040')
        },
        externalCssFiles: ['./node_modules/element-ui/lib/theme-chalk/index.css'], // optional, String or string array. Set external css files (such as cdn css) to extract colors.
        changeSelector(cssSelector) { // optional, Funciton. Changing css selectors, in order to raise css priority, to resolve lazy-loading problems.
          return cssSelector
        },
        isJsUgly: process.env.NODE_ENV !== 'development' // optional. Set to `true` if your js is uglified. Default is set by process.env.NODE_ENV.
      })
---------------------------------

this is my config  and when I npm run dev  find this file size is 0B
![image](https://user-images.githubusercontent.com/17823803/64521724-1a4fc280-d32b-11e9-9db2-9efd49defbaf.png)

--------------------------------

**Comment by hzsrc** [comment]
`matchColors` must be set to your own colors. If no colros matched, it will be empty
