### ISSUE TITLE
页面重复引入css样式有什么好的解决方法吗？

### ISSUE THREAD

**Issue by songStar0904** [hzsrc/vue-element-ui-scaffold-webpack4#7]
element-ui 每个组件样式都有三个重复的。
![image](https://user-images.githubusercontent.com/21984603/68012260-806e1b80-fcc4-11e9-8850-750c33c7da05.png)

**Comment by hzsrc** [comment]
你这是。。好像不是这个项目的吧？

**Comment by hzsrc** [comment]
得看你项目的webpack打包方式了。为了防止下载文件过多，文件之间有重复内容也是有可能的

**Comment by songStar0904** [comment]
我是用了这个项目的插件，elementUi是按需加载的，页面的组件也是异步引入的

**Comment by Pingren** [comment]
@songStar0904 刚刚遇到同样的问题，这里面有解决方案，使用 fast-sass-loader 或者 修改postcss-loader

https://github.com/ElemeFE/element/issues/11817
