### ISSUE TITLE
数组中重复值会出现问题, 

### ISSUE THREAD

**Issue by pengfeiWang** [hzsrc/vue-element-ui-scaffold-webpack4#8]
首先感谢提供这么好的插件
我在使用中发现一个问题, matchColors 是一个数组, 如果数组中出现重复的值的时候可能会对程序处理造成影响
我觉得是对比 oldColor 和 newColor 时, 在去处理匹配的样式时会出问题的
相同的色值, 不一定是相同的class, 是否可以使用 obj 键值对, 具名匹配 class 所对应的变量名称呢, 这样的话, 即使是重复的值也能精准对应到样式上,

在测试中同时发现, oldColor 与 newColor 中相同颜色, 不同位置是貌似也有类似问题

**Comment by hzsrc** [comment]
你好，感谢你的关注，在这里我作了说明：
https://github.com/hzsrc/webpack-theme-color-replacer/issues/29
